/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExpeditorRouteRouteImport } from './routes/expeditor/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExpeditorMyStockRouteImport } from './routes/expeditor/my-stock'
import { Route as AdminMyStockRouteImport } from './routes/admin/my-stock'
import { Route as ExpeditorMachinesIndexRouteImport } from './routes/expeditor/machines/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminMachinesIndexRouteImport } from './routes/admin/machines/index'
import { Route as AdminUsersNewRouteImport } from './routes/admin/users/new'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products/new'
import { Route as AdminMachinesNewRouteImport } from './routes/admin/machines/new'
import { Route as AdminUsersIdIndexRouteImport } from './routes/admin/users/$id.index'
import { Route as ExpeditorMachinesIdOpenShiftRouteImport } from './routes/expeditor/machines/$id.open-shift'
import { Route as ExpeditorMachinesIdCloseShiftRouteImport } from './routes/expeditor/machines/$id.close-shift'
import { Route as AdminUsersIdTransferRouteImport } from './routes/admin/users/$id.transfer'
import { Route as AdminUsersIdEditRouteImport } from './routes/admin/users/$id.edit'
import { Route as AdminProductsIdEditRouteImport } from './routes/admin/products/$id.edit'
import { Route as AdminMachinesIdEditRouteImport } from './routes/admin/machines/$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpeditorRouteRoute = ExpeditorRouteRouteImport.update({
  id: '/expeditor',
  path: '/expeditor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpeditorMyStockRoute = ExpeditorMyStockRouteImport.update({
  id: '/my-stock',
  path: '/my-stock',
  getParentRoute: () => ExpeditorRouteRoute,
} as any)
const AdminMyStockRoute = AdminMyStockRouteImport.update({
  id: '/my-stock',
  path: '/my-stock',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ExpeditorMachinesIndexRoute = ExpeditorMachinesIndexRouteImport.update({
  id: '/machines/',
  path: '/machines/',
  getParentRoute: () => ExpeditorRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMachinesIndexRoute = AdminMachinesIndexRouteImport.update({
  id: '/machines/',
  path: '/machines/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersNewRoute = AdminUsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMachinesNewRoute = AdminMachinesNewRouteImport.update({
  id: '/machines/new',
  path: '/machines/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersIdIndexRoute = AdminUsersIdIndexRouteImport.update({
  id: '/users/$id/',
  path: '/users/$id/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ExpeditorMachinesIdOpenShiftRoute =
  ExpeditorMachinesIdOpenShiftRouteImport.update({
    id: '/machines/$id/open-shift',
    path: '/machines/$id/open-shift',
    getParentRoute: () => ExpeditorRouteRoute,
  } as any)
const ExpeditorMachinesIdCloseShiftRoute =
  ExpeditorMachinesIdCloseShiftRouteImport.update({
    id: '/machines/$id/close-shift',
    path: '/machines/$id/close-shift',
    getParentRoute: () => ExpeditorRouteRoute,
  } as any)
const AdminUsersIdTransferRoute = AdminUsersIdTransferRouteImport.update({
  id: '/users/$id/transfer',
  path: '/users/$id/transfer',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersIdEditRoute = AdminUsersIdEditRouteImport.update({
  id: '/users/$id/edit',
  path: '/users/$id/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsIdEditRoute = AdminProductsIdEditRouteImport.update({
  id: '/products/$id/edit',
  path: '/products/$id/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMachinesIdEditRoute = AdminMachinesIdEditRouteImport.update({
  id: '/machines/$id/edit',
  path: '/machines/$id/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/expeditor': typeof ExpeditorRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/my-stock': typeof AdminMyStockRoute
  '/expeditor/my-stock': typeof ExpeditorMyStockRoute
  '/admin/machines/new': typeof AdminMachinesNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/admin/machines': typeof AdminMachinesIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/expeditor/machines': typeof ExpeditorMachinesIndexRoute
  '/admin/machines/$id/edit': typeof AdminMachinesIdEditRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
  '/admin/users/$id/edit': typeof AdminUsersIdEditRoute
  '/admin/users/$id/transfer': typeof AdminUsersIdTransferRoute
  '/expeditor/machines/$id/close-shift': typeof ExpeditorMachinesIdCloseShiftRoute
  '/expeditor/machines/$id/open-shift': typeof ExpeditorMachinesIdOpenShiftRoute
  '/admin/users/$id': typeof AdminUsersIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/expeditor': typeof ExpeditorRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/my-stock': typeof AdminMyStockRoute
  '/expeditor/my-stock': typeof ExpeditorMyStockRoute
  '/admin/machines/new': typeof AdminMachinesNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/admin/machines': typeof AdminMachinesIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/expeditor/machines': typeof ExpeditorMachinesIndexRoute
  '/admin/machines/$id/edit': typeof AdminMachinesIdEditRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
  '/admin/users/$id/edit': typeof AdminUsersIdEditRoute
  '/admin/users/$id/transfer': typeof AdminUsersIdTransferRoute
  '/expeditor/machines/$id/close-shift': typeof ExpeditorMachinesIdCloseShiftRoute
  '/expeditor/machines/$id/open-shift': typeof ExpeditorMachinesIdOpenShiftRoute
  '/admin/users/$id': typeof AdminUsersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/expeditor': typeof ExpeditorRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/my-stock': typeof AdminMyStockRoute
  '/expeditor/my-stock': typeof ExpeditorMyStockRoute
  '/admin/machines/new': typeof AdminMachinesNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/admin/machines/': typeof AdminMachinesIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/expeditor/machines/': typeof ExpeditorMachinesIndexRoute
  '/admin/machines/$id/edit': typeof AdminMachinesIdEditRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
  '/admin/users/$id/edit': typeof AdminUsersIdEditRoute
  '/admin/users/$id/transfer': typeof AdminUsersIdTransferRoute
  '/expeditor/machines/$id/close-shift': typeof ExpeditorMachinesIdCloseShiftRoute
  '/expeditor/machines/$id/open-shift': typeof ExpeditorMachinesIdOpenShiftRoute
  '/admin/users/$id/': typeof AdminUsersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/expeditor'
    | '/login'
    | '/admin/my-stock'
    | '/expeditor/my-stock'
    | '/admin/machines/new'
    | '/admin/products/new'
    | '/admin/users/new'
    | '/admin/machines'
    | '/admin/products'
    | '/admin/users'
    | '/expeditor/machines'
    | '/admin/machines/$id/edit'
    | '/admin/products/$id/edit'
    | '/admin/users/$id/edit'
    | '/admin/users/$id/transfer'
    | '/expeditor/machines/$id/close-shift'
    | '/expeditor/machines/$id/open-shift'
    | '/admin/users/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/expeditor'
    | '/login'
    | '/admin/my-stock'
    | '/expeditor/my-stock'
    | '/admin/machines/new'
    | '/admin/products/new'
    | '/admin/users/new'
    | '/admin/machines'
    | '/admin/products'
    | '/admin/users'
    | '/expeditor/machines'
    | '/admin/machines/$id/edit'
    | '/admin/products/$id/edit'
    | '/admin/users/$id/edit'
    | '/admin/users/$id/transfer'
    | '/expeditor/machines/$id/close-shift'
    | '/expeditor/machines/$id/open-shift'
    | '/admin/users/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/expeditor'
    | '/login'
    | '/admin/my-stock'
    | '/expeditor/my-stock'
    | '/admin/machines/new'
    | '/admin/products/new'
    | '/admin/users/new'
    | '/admin/machines/'
    | '/admin/products/'
    | '/admin/users/'
    | '/expeditor/machines/'
    | '/admin/machines/$id/edit'
    | '/admin/products/$id/edit'
    | '/admin/users/$id/edit'
    | '/admin/users/$id/transfer'
    | '/expeditor/machines/$id/close-shift'
    | '/expeditor/machines/$id/open-shift'
    | '/admin/users/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ExpeditorRouteRoute: typeof ExpeditorRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expeditor': {
      id: '/expeditor'
      path: '/expeditor'
      fullPath: '/expeditor'
      preLoaderRoute: typeof ExpeditorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expeditor/my-stock': {
      id: '/expeditor/my-stock'
      path: '/my-stock'
      fullPath: '/expeditor/my-stock'
      preLoaderRoute: typeof ExpeditorMyStockRouteImport
      parentRoute: typeof ExpeditorRouteRoute
    }
    '/admin/my-stock': {
      id: '/admin/my-stock'
      path: '/my-stock'
      fullPath: '/admin/my-stock'
      preLoaderRoute: typeof AdminMyStockRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/expeditor/machines/': {
      id: '/expeditor/machines/'
      path: '/machines'
      fullPath: '/expeditor/machines'
      preLoaderRoute: typeof ExpeditorMachinesIndexRouteImport
      parentRoute: typeof ExpeditorRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/machines/': {
      id: '/admin/machines/'
      path: '/machines'
      fullPath: '/admin/machines'
      preLoaderRoute: typeof AdminMachinesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/new': {
      id: '/admin/users/new'
      path: '/users/new'
      fullPath: '/admin/users/new'
      preLoaderRoute: typeof AdminUsersNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/machines/new': {
      id: '/admin/machines/new'
      path: '/machines/new'
      fullPath: '/admin/machines/new'
      preLoaderRoute: typeof AdminMachinesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/$id/': {
      id: '/admin/users/$id/'
      path: '/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/expeditor/machines/$id/open-shift': {
      id: '/expeditor/machines/$id/open-shift'
      path: '/machines/$id/open-shift'
      fullPath: '/expeditor/machines/$id/open-shift'
      preLoaderRoute: typeof ExpeditorMachinesIdOpenShiftRouteImport
      parentRoute: typeof ExpeditorRouteRoute
    }
    '/expeditor/machines/$id/close-shift': {
      id: '/expeditor/machines/$id/close-shift'
      path: '/machines/$id/close-shift'
      fullPath: '/expeditor/machines/$id/close-shift'
      preLoaderRoute: typeof ExpeditorMachinesIdCloseShiftRouteImport
      parentRoute: typeof ExpeditorRouteRoute
    }
    '/admin/users/$id/transfer': {
      id: '/admin/users/$id/transfer'
      path: '/users/$id/transfer'
      fullPath: '/admin/users/$id/transfer'
      preLoaderRoute: typeof AdminUsersIdTransferRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/$id/edit': {
      id: '/admin/users/$id/edit'
      path: '/users/$id/edit'
      fullPath: '/admin/users/$id/edit'
      preLoaderRoute: typeof AdminUsersIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/$id/edit': {
      id: '/admin/products/$id/edit'
      path: '/products/$id/edit'
      fullPath: '/admin/products/$id/edit'
      preLoaderRoute: typeof AdminProductsIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/machines/$id/edit': {
      id: '/admin/machines/$id/edit'
      path: '/machines/$id/edit'
      fullPath: '/admin/machines/$id/edit'
      preLoaderRoute: typeof AdminMachinesIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminMyStockRoute: typeof AdminMyStockRoute
  AdminMachinesNewRoute: typeof AdminMachinesNewRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminUsersNewRoute: typeof AdminUsersNewRoute
  AdminMachinesIndexRoute: typeof AdminMachinesIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminMachinesIdEditRoute: typeof AdminMachinesIdEditRoute
  AdminProductsIdEditRoute: typeof AdminProductsIdEditRoute
  AdminUsersIdEditRoute: typeof AdminUsersIdEditRoute
  AdminUsersIdTransferRoute: typeof AdminUsersIdTransferRoute
  AdminUsersIdIndexRoute: typeof AdminUsersIdIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminMyStockRoute: AdminMyStockRoute,
  AdminMachinesNewRoute: AdminMachinesNewRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminUsersNewRoute: AdminUsersNewRoute,
  AdminMachinesIndexRoute: AdminMachinesIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminMachinesIdEditRoute: AdminMachinesIdEditRoute,
  AdminProductsIdEditRoute: AdminProductsIdEditRoute,
  AdminUsersIdEditRoute: AdminUsersIdEditRoute,
  AdminUsersIdTransferRoute: AdminUsersIdTransferRoute,
  AdminUsersIdIndexRoute: AdminUsersIdIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ExpeditorRouteRouteChildren {
  ExpeditorMyStockRoute: typeof ExpeditorMyStockRoute
  ExpeditorMachinesIndexRoute: typeof ExpeditorMachinesIndexRoute
  ExpeditorMachinesIdCloseShiftRoute: typeof ExpeditorMachinesIdCloseShiftRoute
  ExpeditorMachinesIdOpenShiftRoute: typeof ExpeditorMachinesIdOpenShiftRoute
}

const ExpeditorRouteRouteChildren: ExpeditorRouteRouteChildren = {
  ExpeditorMyStockRoute: ExpeditorMyStockRoute,
  ExpeditorMachinesIndexRoute: ExpeditorMachinesIndexRoute,
  ExpeditorMachinesIdCloseShiftRoute: ExpeditorMachinesIdCloseShiftRoute,
  ExpeditorMachinesIdOpenShiftRoute: ExpeditorMachinesIdOpenShiftRoute,
}

const ExpeditorRouteRouteWithChildren = ExpeditorRouteRoute._addFileChildren(
  ExpeditorRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ExpeditorRouteRoute: ExpeditorRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
