/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExpeditorRouteRouteImport } from './routes/expeditor/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExpeditorMachinesRouteImport } from './routes/expeditor/machines'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminMachinesIndexRouteImport } from './routes/admin/machines/index'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products/new'
import { Route as AdminMachinesNewRouteImport } from './routes/admin/machines/new'
import { Route as AdminProductsIdEditRouteImport } from './routes/admin/products/$id.edit'
import { Route as AdminMachinesIdEditRouteImport } from './routes/admin/machines/$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpeditorRouteRoute = ExpeditorRouteRouteImport.update({
  id: '/expeditor',
  path: '/expeditor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpeditorMachinesRoute = ExpeditorMachinesRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => ExpeditorRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMachinesIndexRoute = AdminMachinesIndexRouteImport.update({
  id: '/machines/',
  path: '/machines/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMachinesNewRoute = AdminMachinesNewRouteImport.update({
  id: '/machines/new',
  path: '/machines/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsIdEditRoute = AdminProductsIdEditRouteImport.update({
  id: '/products/$id/edit',
  path: '/products/$id/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMachinesIdEditRoute = AdminMachinesIdEditRouteImport.update({
  id: '/machines/$id/edit',
  path: '/machines/$id/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/expeditor': typeof ExpeditorRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/expeditor/machines': typeof ExpeditorMachinesRoute
  '/admin/machines/new': typeof AdminMachinesNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/machines': typeof AdminMachinesIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/machines/$id/edit': typeof AdminMachinesIdEditRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/expeditor': typeof ExpeditorRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/expeditor/machines': typeof ExpeditorMachinesRoute
  '/admin/machines/new': typeof AdminMachinesNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/machines': typeof AdminMachinesIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/machines/$id/edit': typeof AdminMachinesIdEditRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/expeditor': typeof ExpeditorRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/expeditor/machines': typeof ExpeditorMachinesRoute
  '/admin/machines/new': typeof AdminMachinesNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/machines/': typeof AdminMachinesIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/machines/$id/edit': typeof AdminMachinesIdEditRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/expeditor'
    | '/login'
    | '/admin/users'
    | '/expeditor/machines'
    | '/admin/machines/new'
    | '/admin/products/new'
    | '/admin/machines'
    | '/admin/products'
    | '/admin/machines/$id/edit'
    | '/admin/products/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/expeditor'
    | '/login'
    | '/admin/users'
    | '/expeditor/machines'
    | '/admin/machines/new'
    | '/admin/products/new'
    | '/admin/machines'
    | '/admin/products'
    | '/admin/machines/$id/edit'
    | '/admin/products/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/expeditor'
    | '/login'
    | '/admin/users'
    | '/expeditor/machines'
    | '/admin/machines/new'
    | '/admin/products/new'
    | '/admin/machines/'
    | '/admin/products/'
    | '/admin/machines/$id/edit'
    | '/admin/products/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ExpeditorRouteRoute: typeof ExpeditorRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expeditor': {
      id: '/expeditor'
      path: '/expeditor'
      fullPath: '/expeditor'
      preLoaderRoute: typeof ExpeditorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expeditor/machines': {
      id: '/expeditor/machines'
      path: '/machines'
      fullPath: '/expeditor/machines'
      preLoaderRoute: typeof ExpeditorMachinesRouteImport
      parentRoute: typeof ExpeditorRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/machines/': {
      id: '/admin/machines/'
      path: '/machines'
      fullPath: '/admin/machines'
      preLoaderRoute: typeof AdminMachinesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/machines/new': {
      id: '/admin/machines/new'
      path: '/machines/new'
      fullPath: '/admin/machines/new'
      preLoaderRoute: typeof AdminMachinesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/$id/edit': {
      id: '/admin/products/$id/edit'
      path: '/products/$id/edit'
      fullPath: '/admin/products/$id/edit'
      preLoaderRoute: typeof AdminProductsIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/machines/$id/edit': {
      id: '/admin/machines/$id/edit'
      path: '/machines/$id/edit'
      fullPath: '/admin/machines/$id/edit'
      preLoaderRoute: typeof AdminMachinesIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminUsersRoute: typeof AdminUsersRoute
  AdminMachinesNewRoute: typeof AdminMachinesNewRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminMachinesIndexRoute: typeof AdminMachinesIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminMachinesIdEditRoute: typeof AdminMachinesIdEditRoute
  AdminProductsIdEditRoute: typeof AdminProductsIdEditRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminUsersRoute: AdminUsersRoute,
  AdminMachinesNewRoute: AdminMachinesNewRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminMachinesIndexRoute: AdminMachinesIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminMachinesIdEditRoute: AdminMachinesIdEditRoute,
  AdminProductsIdEditRoute: AdminProductsIdEditRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ExpeditorRouteRouteChildren {
  ExpeditorMachinesRoute: typeof ExpeditorMachinesRoute
}

const ExpeditorRouteRouteChildren: ExpeditorRouteRouteChildren = {
  ExpeditorMachinesRoute: ExpeditorMachinesRoute,
}

const ExpeditorRouteRouteWithChildren = ExpeditorRouteRoute._addFileChildren(
  ExpeditorRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ExpeditorRouteRoute: ExpeditorRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
